import type { Metadata } from "next";
import "./globals.css";
import { PoppinsFont } from "@/Fonts";
import { twJoin } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Portfólio - Saulo Felipe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="scroll-smooth" lang="pt-br">
      <body className={twJoin(PoppinsFont.className, "bg-black-1 overflow-x-hidden")}>
        {children}
      </body>
    </html>
  );
}
